-- MySQL Workbench Synchronization
-- Generated: 2019-03-31 16:58
-- Model: New Model
-- Version: 1.0
-- Project: Name of the project
-- Author: coagus

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

CREATE SCHEMA IF NOT EXISTS `TimeAppDB` DEFAULT CHARACTER SET utf8 ;

CREATE TABLE IF NOT EXISTS `TimeAppDB`.`Activity` (
  `Id` INT(11) NOT NULL AUTO_INCREMENT,
  `Name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`Id`),
  UNIQUE INDEX `Name_UNIQUE` (`Name` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

CREATE TABLE IF NOT EXISTS `TimeAppDB`.`TimeResult` (
  `Id` INT(11) NOT NULL AUTO_INCREMENT,
  `Activity_Id` INT(11) NOT NULL,
  `Start` TIMESTAMP NULL DEFAULT current_timestamp,
  `Seconds` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`Id`),
  INDEX `fk_TimeResult_Activity_idx` (`Activity_Id` ASC),
  UNIQUE INDEX `Start_UNIQUE` (`Start` ASC),
  CONSTRAINT `fk_TimeResult_Activity`
    FOREIGN KEY (`Activity_Id`)
    REFERENCES `TimeAppDB`.`Activity` (`Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
